In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [27]:
b = np.array([[1,3,4,5,2],[7,75,23,3,1]])
b

array([[ 1,  3,  4,  5,  2],
       [ 7, 75, 23,  3,  1]])

In [12]:
b.shape

(2, 5)

In [28]:
b.dtype

dtype('int32')

In [30]:
np.arange(10,25,5)

array([10, 15, 20])

In [32]:
np.arange(0, 5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [33]:
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
# gets all the rows
b[0,:]

array([1, 3, 4, 5, 2])

In [18]:
# gets all the column
b[:,0:3]

array([[ 1,  3,  4],
       [ 7, 75, 23]])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full((2,3),55)

array([[55, 55, 55],
       [55, 55, 55]])

In [24]:
np.full_like(a,55)

array([55, 55, 55])

In [27]:
np.random.rand(4,2)

array([[0.17003876, 0.45579565],
       [0.65283813, 0.33216238],
       [0.2636605 , 0.60762248],
       [0.53504347, 0.25857867]])

In [36]:
np.random.randint(745,size=(3,3))

array([[303, 452, 744],
       [718, 296, 732],
       [258, 458, 517]])

In [39]:
arr = np.array([[1,2,4]])
r1  = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [41]:
trial_array = np.ones((5,5))
trial_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
trial_array[1:-1,1:-1] = np.zeros((3,3))
trial_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
trial_array[2,2] = 9
trial_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## maths in numpy

In [61]:
sampleMath = np.array([1,2,3,4,5,6])
sampleMath

array([1, 2, 3, 4, 5, 6])

In [65]:
sampleMath + 2

array([3, 4, 5, 6, 7, 8])

In [66]:
sampleMath - 2

array([-1,  0,  1,  2,  3,  4])


## linear Algebra

In [74]:
w =np.ones((2,3))

q =np.full((3,2),2)
print(q)
print(w)
np.matmul(w,q)

[[2 2]
 [2 2]
 [2 2]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[6., 6.],
       [6., 6.]])

## Statistics

In [3]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.min(stats)

1

In [5]:
np.min(stats, axis=1)

array([1, 4])

In [6]:
np.max(stats)

6

In [7]:
np.max(stats, axis=1)

array([3, 6])

In [9]:
np.sum(stats)

21

In [10]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganizing Arrays

In [11]:
before = np.array([[1,2,3,4],[5,6,7,8]])


In [15]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
# ertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Loading Data from File

In [23]:
# fileData = np.genfromtxt('file name', delimiter=',')

## boolean masking and advance indexing

In [24]:
# fileData > 50 returns file data with true and falses
# fileData[fileData > 50]  returns a list containinf=d data greater than 50